### Explicit Random Walk

In [1]:
import numpy as np
from scipy.linalg import fractional_matrix_power
from numpy.linalg import matrix_power
from numpy import matmul

In [2]:
A = np.array([
    [0, 1, 0, 0, 0],
    [1, 0, 0, 1, 0], 
    [0, 0, 0, 1, 0],
    [0, 1, 1, 0, 1],
    [0, 0, 0, 1, 0]],
    dtype=float
)
I = np.eye(A.shape[0])
A = A + I  
A

array([[1., 1., 0., 0., 0.],
       [1., 1., 0., 1., 0.],
       [0., 0., 1., 1., 0.],
       [0., 1., 1., 1., 1.],
       [0., 0., 0., 1., 1.]])

In [3]:
def get_diag(D):
    return np.array(np.diag(D))

def get_T(A, D):
    T = np.matmul(matrix_power(D, -1), A)
    return T

def get_A_hat_power(k, A, D, T):
    print(type(D))
    D_nsqrt = fractional_matrix_power(D, -0.5)
    T_power = matrix_power(T, k-1)
    A_hat = matmul(D_nsqrt, matmul(A, matmul(T_power, D_nsqrt)))
    return A_hat

In [4]:
D = np.array(np.sum(A, axis=1))    # calculates degree of each node
D = get_diag(D)    # get diagonal node degree matrix
T = get_T(A, D)    # calculcate transition matrix

In [5]:
A_hat_1 = get_A_hat_power(1, A, D, T)  # performs k-step (in this case, 1) random walk 
A_hat_1    # same as normalized version of A [since T^0 = 1]

<class 'numpy.ndarray'>


array([[0.5       , 0.40824829, 0.        , 0.        , 0.        ],
       [0.40824829, 0.33333333, 0.        , 0.28867513, 0.        ],
       [0.        , 0.        , 0.5       , 0.35355339, 0.        ],
       [0.        , 0.28867513, 0.35355339, 0.25      , 0.35355339],
       [0.        , 0.        , 0.        , 0.35355339, 0.5       ]])

In [6]:
A_hat_2 = get_A_hat_power(2, A, D, T)
A_hat_2

<class 'numpy.ndarray'>


array([[0.41666667, 0.34020691, 0.        , 0.11785113, 0.        ],
       [0.34020691, 0.36111111, 0.10206207, 0.16839383, 0.10206207],
       [0.        , 0.10206207, 0.375     , 0.26516504, 0.125     ],
       [0.11785113, 0.16839383, 0.26516504, 0.39583333, 0.26516504],
       [0.        , 0.10206207, 0.125     , 0.26516504, 0.375     ]])

In [7]:
A_hat_3 = get_A_hat_power(3, A, D, T)
A_hat_3

<class 'numpy.ndarray'>


array([[0.34722222, 0.31752645, 0.04166667, 0.12767206, 0.04166667],
       [0.31752645, 0.30787037, 0.11056725, 0.21851104, 0.11056725],
       [0.04166667, 0.11056725, 0.28125   , 0.27253074, 0.15625   ],
       [0.12767206, 0.21851104, 0.27253074, 0.33506944, 0.27253074],
       [0.04166667, 0.11056725, 0.15625   , 0.27253074, 0.28125   ]])